### ISSUE TITLE
com.cs451.checkers.Board.between(Position, Position) returns wrong position, possibly?

### ISSUE THREAD

**Issue by ajc-developer** [Jugal112/cs451_checkers#13]
Run test case for board to see the issue.

![buggy](https://cloud.githubusercontent.com/assets/8146286/17707468/8ba74d08-63ae-11e6-8b0a-5b342f2f8511.PNG)
In this image, S is the source position, D is the destination, E is the expected result, and B is the actual result, unless I am understanding incorrectly.

**Comment by Jugal112** [comment]
whoops you're right forgot to divide by 2

**Comment by ajc-developer** [comment]
That's what I thought it was, but wasn't sure. haha
